version: '3.1'

services:

  python-nginx:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: python-nginx
    ports:
      - 80:80
    volumes:
      - ./workspace:/workspace
    tty: true
